# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'entrenate v2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for entrenate v2
  pod 'Appirater'
  pod 'SDWebImage'
  pod 'Firebase'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'
  pod 'Firebase/Performance'
  pod 'Firebase/Storage'
  pod 'Cards'
  pod 'ShimmerSwift'
  pod 'RAMAnimatedTabBarController'
  pod 'TransitionButton'
  pod 'SAConfettiView'



end
