# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'entrenate v2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for entrenate v2
  pod 'Appirater'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'

end
