# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'entrenate' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for entrenate
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'FirebaseUI/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'FirebaseUI/Google'
  pod 'FirebaseUI/Facebook'
  pod 'FirebaseUI/OAuth'
  pod 'FirebaseUI/Phone'
  pod 'GoogleSignIn'
  pod 'Firebase/Storage'

end
